name: Run Selenium Script on Safari

on:
  push:
    branches:
      - main  # Trigger workflow on push to main branch
  pull_request:
    branches:
      - main  # Trigger workflow on pull requests targeting the main branch

  # Schedule the workflow to run every 6 hours
  schedule:
    - cron: '0 */6 * * *'  # Cron expression for running every 6 hours

jobs:
  selenium:
    runs-on: macos-latest  # GitHub Actions supports Safari on macOS

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Enable SafariDriver
        run: |
          sudo safaridriver --enable

      - name: Run Selenium script
        run: |
          python test_selenium.py
